#!/bin/bash -l
set -x
compile_all=1
#DEBUG=YES
DEBUG=NO

#make sure to load modules
# source ../stochy_mods_gaeac6 or ../stocy_mods_ursa

#FC=ftn #ifort
#MPIF90=ftn  #mpiifort

FMS_INC=${fms_ROOT}/include_r8
FMS_LIB=${fms_ROOT}/lib
ESMF_INC=${esmf_ROOT}/include
ESMF_LIB=${esmf_ROOT}/lib
NETCDF_INC=${netcdf_c_ROOT}/include  #NETCDF}/include
NETCDF_LIB=${netcdf_c_ROOT}/lib
NETCDF_F_INC=${netcdf_fortran_ROOT}/include  #NETCDF}/include
NETCDF_F_LIB=${netcdf_fortran_ROOT}/lib
HDF5_INC=${hdf5_ROOT}/include
HDF5_LIB=${hdf5_ROOT}/lib
ZLIB_INC=${zlib_ROOT}/include
ZLIB_LIB=${zlib_ROOT}/lib
LPACK_INC=${OPENBLAS_ROOT:-$OLCF_OPENBLAS_ROOT}/include   #openblas_ROOT}/include 
LPACK_LIB=${OPENBLAS_ROOT:-$OLCF_OPENBLAS_ROOT}/lib
PNETCDF_ROOT=${parallel_netcdf_ROOT:-/contrib/spack-stack/spack-stack-1.9.2/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/parallel-netcdf-1.12.3-oeqtpxg/}
PNETCDF_LIB=$PNETCDF_ROOT/lib
PNETCDF_INC=$PNETCDF_ROOT/include
PIO_ROOT=${parallelio_ROOT:-/contrib/spack-stack/spack-stack-1.9.2/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/parallelio-2.6.2-pmg6l7r/lib}
PIO_LIB=$PIO_ROOT/lib
PIO_INC=$PIO_ROOT/include

rm EnsGen.x *.o *.a

INCS="-I. -I${FMS_INC} -I${ESMF_INC} -I${NETCDF_INC} -I${NETCDF_F_INC} -I${PNETCDF_INC} -I${PIO_INC}"
if [ $DEBUG == 'YES' ]; then
   FLAGS=" -O0 -g -check all -link_mpi=dbg_mt -traceback -real-size 64 -qopenmp -c "$INCS
else
   FLAGS=" -traceback -real-size 64 -qopenmp -c "$INCS
fi

if [ $compile_all -eq 1 ];then
   rm -f *.i90 *.i *.o *.mod lib*a
   ${MPIF90} ${FLAGS} stochastic_physics/kinddef.F90
   ${MPIF90} ${FLAGS} stochastic_physics/mpi_wrapper.F90
   ${MPIF90} ${FLAGS} stochastic_physics/unit_tests/fv_arrays_stub.F90
   ${MPIF90} ${FLAGS} stochastic_physics/unit_tests/fv_mp_stub_mod.F90
   ${MPIF90} ${FLAGS} stochastic_physics/unit_tests/fv_control_stub.F90
   ${MPIF90} ${FLAGS} stochastic_physics/unit_tests/atmosphere_stub.F90
   ${MPIF90} ${FLAGS} stochastic_physics/mersenne_twister.F90
   ${MPIF90} ${FLAGS} stochastic_physics/stochy_internal_state_mod.F90
   ${MPIF90} ${FLAGS} stochastic_physics/stochy_namelist_def.F90
   ${MPIF90} ${FLAGS} stochastic_physics/spectral_transforms.F90
   ${MPIF90} ${FLAGS} stochastic_physics/compns_stochy.F90
   ${MPIF90} ${FLAGS} stochastic_physics/stochy_patterngenerator.F90
   ${MPIF90} ${FLAGS} stochastic_physics/stochy_data_mod.F90
   ${MPIF90} ${FLAGS} stochastic_physics/get_stochy_pattern.F90
   ${MPIF90} ${FLAGS} stochastic_physics/lndp_apply_perts.F90
   ${MPIF90} ${FLAGS} stochastic_physics/stochastic_physics.F90
fi
   
ar rv libstochastic_physics.a *.o

if [ $DEBUG == 'YES' ]; then
   ${MPIF90} -traceback -g -C -real-size 64 -qopenmp -o EnsGen.x land_ens_gen.f90 ${INCS} -L. -lstochastic_physics -L${FMS_LIB} -lfms_r8 -L${ESMF_LIB} -Wl,-rpath,${ESMF_LIB} -L${PNETCDF_LIB} -L${ESMF_LIB} -lesmf -L${NETCDF_LIB} -lnetcdf -L${NETCDF_F_LIB} -lnetcdff -L${ZLIB_LIB} -lz -L${LPACK_LIB} -lopenblas -L${PIO_LIB} -lpioc -lpiof  # -llapack -lblas    # -L${HDF5_LIB} -lhdf5_hl -lhdf5
else
   ${MPIF90} -traceback -real-size 64 -qopenmp -o EnsGen.x land_ens_gen.f90 ${INCS} -L. -lstochastic_physics -L${FMS_LIB} -lfms_r8 -L${ESMF_LIB} -Wl,-rpath,${ESMF_LIB} -L${PNETCDF_LIB} -L${ESMF_LIB} -lesmf -L${NETCDF_LIB} -lnetcdf -L${NETCDF_F_LIB} -lnetcdff -L${ZLIB_LIB} -lz -L${LPACK_LIB} -lopenblas -L${PIO_LIB} -lpioc -lpiof     # -llapack -lblas    # -L${HDF5_LIB} -lhdf5_hl -lhdf5 
fi
